import type { MoneyMinor, TradingOsResult } from "./contracts";
import { contractFloor, moneyMultiplyInteger, moneySubtract } from "./financialMath";
export type BreachReplayInput = Readonly<{ tradeId: string | null; occurredAt: string | null; ruleId: string | null; ruleValueMinor: MoneyMinor | null; accountValueBeforeMinor: MoneyMinor | null; accountValueAfterMinor: MoneyMinor | null; bufferBeforeMinor: MoneyMinor | null; plannedRiskMinor: MoneyMinor | null; actualRiskMinor: MoneyMinor | null; actualContracts: number | null; recommendedContracts: number | null }>;
export type BreachReplayValues = Readonly<{ triggeringTradeId: string; occurredAt: string; ruleId: string; ruleValueMinor: MoneyMinor; accountValueBeforeMinor: MoneyMinor; accountValueAfterMinor: MoneyMinor; bufferBeforeMinor: MoneyMinor; bufferAfterMinor: MoneyMinor; plannedRiskMinor: MoneyMinor; actualRiskMinor: MoneyMinor; breachAmountMinor: MoneyMinor; counterfactual: Readonly<{ contracts: number; projectedRiskMinor: MoneyMinor; projectedRemainingBufferMinor: MoneyMinor; accountWouldRemainActive: boolean; changesMarketOutcome: false }> }>;

export function createBreachReplay(input: BreachReplayInput | null): TradingOsResult<BreachReplayValues | null> {
  if (!input) return result("needs_input", null, ["breach_not_recorded"], ["breach_fact"]);
  const missing = Object.entries(input).filter(([, value]) => value == null || (typeof value === "string" && !value.trim())).map(([key]) => `breach_${key}`);
  if (missing.length || !valid(input)) return result("needs_input", null, ["breach_replay_data_missing_or_invalid"], missing.length ? missing : ["breach_values"]);
  const perContractRisk = contractFloor(input.actualRiskMinor!, input.actualContracts!);
  const projectedRisk = moneyMultiplyInteger(perContractRisk, input.recommendedContracts!);
  const projectedRemaining = moneySubtract(input.bufferBeforeMinor!, projectedRisk);
  return result("rule_violation", { triggeringTradeId: input.tradeId!, occurredAt: input.occurredAt!, ruleId: input.ruleId!, ruleValueMinor: input.ruleValueMinor!, accountValueBeforeMinor: input.accountValueBeforeMinor!, accountValueAfterMinor: input.accountValueAfterMinor!, bufferBeforeMinor: input.bufferBeforeMinor!, bufferAfterMinor: moneySubtract(input.bufferBeforeMinor!, input.actualRiskMinor!), plannedRiskMinor: input.plannedRiskMinor!, actualRiskMinor: input.actualRiskMinor!, breachAmountMinor: Math.max(0, moneySubtract(input.actualRiskMinor!, input.bufferBeforeMinor!)), counterfactual: { contracts: input.recommendedContracts!, projectedRiskMinor: projectedRisk, projectedRemainingBufferMinor: projectedRemaining, accountWouldRemainActive: projectedRemaining >= 0, changesMarketOutcome: false } }, ["recorded_rule_breach"], []);
}
function valid(input: BreachReplayInput): boolean { return Number.isSafeInteger(input.actualContracts) && input.actualContracts! > 0 && Number.isSafeInteger(input.recommendedContracts) && input.recommendedContracts! >= 0 && !Number.isNaN(Date.parse(input.occurredAt!)) && [input.ruleValueMinor, input.accountValueBeforeMinor, input.accountValueAfterMinor, input.bufferBeforeMinor, input.plannedRiskMinor, input.actualRiskMinor].every((value) => Number.isSafeInteger(value)); }
function result(status: TradingOsResult<BreachReplayValues | null>["status"], values: BreachReplayValues | null, reasons: string[], missingInputs: string[]): TradingOsResult<BreachReplayValues | null> { return { values, status, reasons, missingInputs, appliedHardLimits: [], relatedRuleIds: values ? [values.ruleId] : [] }; }
