import type { DailyTradingPlanSnapshot } from "./dailyPlan";
import type { MoneyMinor } from "./contracts";
import { formatMoneyMinor } from "./financialMath";
export type DecisionVerdict = "good_decision" | "within_plan" | "risky_decision" | "plan_violation" | "rule_violation" | "insufficient_data";
export type DecisionReplayInput = { plan: DailyTradingPlanSnapshot | null; trade: { id: string; riskMinor: MoneyMinor | null; realizedPnlMinor: MoneyMinor | null; sequenceToday: number | null; ruleViolationId?: string | null; dailyBufferAfterMinor?: MoneyMinor | null } | null };
export type DecisionReplay = { verdict: DecisionVerdict; reason: string; mathematicalConsequence: string; nextAction: string; relatedTradeId: string | null; relatedRuleId: string | null; planRiskMinor: MoneyMinor | null; actualRiskMinor: MoneyMinor | null; journalTradeId: string | null };
export function createDecisionReplay(input: DecisionReplayInput): DecisionReplay {
  const trade = input.trade; const plan = input.plan;
  if (!plan || !trade || trade.riskMinor == null || trade.sequenceToday == null) return replay("insufficient_data", "A frozen plan or complete trade facts are unavailable.", "No decision quality is inferred.", "Save the plan before taking the next trade.", trade?.id ?? null, null, plan?.riskPerTradeMinor ?? null, trade?.riskMinor ?? null);
  if (trade.ruleViolationId) return replay("rule_violation", `Recorded rule ${trade.ruleViolationId} was violated.`, `Risk used: $${formatMoneyMinor(trade.riskMinor)} of $${formatMoneyMinor(plan.riskPerTradeMinor)}.`, "Stop and review the breached rule.", trade.id, trade.ruleViolationId, plan.riskPerTradeMinor, trade.riskMinor);
  if (trade.sequenceToday > plan.maximumTrades || (plan.stopAfterLosses != null && trade.sequenceToday > plan.maximumTrades)) return replay("plan_violation", `This was trade #${trade.sequenceToday} against a ${plan.maximumTrades}-trade plan.`, `Risk used: $${formatMoneyMinor(trade.riskMinor)} of $${formatMoneyMinor(plan.riskPerTradeMinor)}.`, "Stop trading for today.", trade.id, "trade_count", plan.riskPerTradeMinor, trade.riskMinor);
  if (trade.riskMinor > plan.riskPerTradeMinor) return replay("risky_decision", "The trade exceeded the frozen per-trade risk plan.", `Risk used: $${formatMoneyMinor(trade.riskMinor)} of $${formatMoneyMinor(plan.riskPerTradeMinor)}.`, "Use the planned size on the next qualified setup.", trade.id, "per_trade_risk", plan.riskPerTradeMinor, trade.riskMinor);
  return replay("good_decision", "The trade stayed within the frozen plan.", `Risk used: $${formatMoneyMinor(trade.riskMinor)} of $${formatMoneyMinor(plan.riskPerTradeMinor)}. Daily buffer after trade: $${formatMoneyMinor(trade.dailyBufferAfterMinor ?? 0)}.`, "Keep the same position size for the next qualified setup.", trade.id, null, plan.riskPerTradeMinor, trade.riskMinor);
}
function replay(verdict: DecisionVerdict, reason: string, mathematicalConsequence: string, nextAction: string, relatedTradeId: string | null, relatedRuleId: string | null, planRiskMinor: MoneyMinor | null, actualRiskMinor: MoneyMinor | null): DecisionReplay { return { verdict, reason, mathematicalConsequence, nextAction, relatedTradeId, relatedRuleId, planRiskMinor, actualRiskMinor, journalTradeId: relatedTradeId }; }
