#!/usr/bin/env bash
# Build fresh Release-Staging 1.6.1 (113) for physical device from current HEAD.
# Does NOT bump CFBundleVersion. Metro OFF. Staging Supabase only.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

EXPECTED_VERSION="${YT_EXPECTED_VERSION:-1.6.1}"
EXPECTED_BUILD="${YT_EXPECTED_BUILD:-113}"
DEVICE_ID="${YT_PHYSICAL_DEVICE_ID:-6FCFF771-7154-5CC0-BC29-858A3C376CAF}"
DD_PATH="${YT_RS113_DERIVED_DATA:-$ROOT/build/DerivedData-yt3-qa-head}"
APP_OUT="$DD_PATH/Build/Products/Release-Staging-iphoneos/YouTrader.app"
ART="${YT_QA_ARTIFACTS_DIR:-$ROOT/docs/releases/1.6.1/qa-artifacts}"
EVID="${YT_PHYSICAL_EVIDENCE_DIR:-$ROOT/docs/releases/1.6.1/evidence/phase4f-fresh-rs113-head}"
STAGING_HOST="zleojeqkzizeyerhjpur.supabase.co"
PROD_HOST="izzrlsgumyabdvlmwlwn.supabase.co"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$ART" "$EVID"

GIT_SHA="$(git rev-parse --short HEAD)"
GIT_FULL="$(git rev-parse HEAD)"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BUNDLE_MARKER="embedded-main.jsbundle"

log() { echo "$*" | tee -a "$ART/build-rs113-head-$STAMP.log"; }

log "build_rs113_head start sha=$GIT_SHA full=$GIT_FULL time=$BUILD_TIME"

# Refuse production bump / wrong identity
ver_json="$(node -e "const a=require('./app.json'); process.stdout.write(String(a.expo?.ios?.buildNumber||''))")"
[[ "$ver_json" == "$EXPECTED_BUILD" ]] || { log "error: app.json buildNumber=$ver_json expected=$EXPECTED_BUILD"; exit 4; }

[[ -f ios/.xcode.env.staging ]] || { log "error: missing ios/.xcode.env.staging"; exit 2; }

# Generate embeddable fingerprint constants (Metro may not inline custom EXPO_PUBLIC_YT_*).
cat > src/config/buildFingerprint.generated.ts <<EOF
/**
 * GENERATED — do not edit by hand.
 * Written by scripts/qa/build-release-staging-113-device.sh at $BUILD_TIME
 */
export const GENERATED_APP_ENV = "staging";

export const GENERATED_BUILD_FINGERPRINT = {
  gitSha: "$GIT_SHA",
  buildTimeUtc: "$BUILD_TIME",
  version: "$EXPECTED_VERSION",
  buildNumber: "$EXPECTED_BUILD",
  xcodeConfiguration: "Release-Staging",
  embeddedBundleMarker: "$BUNDLE_MARKER",
} as const;
EOF
log "wrote src/config/buildFingerprint.generated.ts"

# Staging env + fingerprint env fallback (local only — do not commit .xcode.env.local)
{
  cat ios/.xcode.env.staging
  echo ""
  echo "# Generated by build-release-staging-113-device.sh — DO NOT COMMIT"
  echo "export EXPO_PUBLIC_YT_GIT_SHA=$GIT_SHA"
  echo "export EXPO_PUBLIC_YT_BUILD_TIME=$BUILD_TIME"
  echo "export EXPO_PUBLIC_YT_APP_VERSION=$EXPECTED_VERSION"
  echo "export EXPO_PUBLIC_YT_BUILD_NUMBER=$EXPECTED_BUILD"
  echo "export EXPO_PUBLIC_YT_XCODE_CONFIG=Release-Staging"
  echo "export EXPO_PUBLIC_YT_BUNDLE_MARKER=$BUNDLE_MARKER"
  echo "export EXPO_PUBLIC_YT_SHOW_BUILD_FP=1"
} > ios/.xcode.env.local

# Remove only stale YouTrader derived outputs for this pipeline (keep archives for diagnosis)
log "cleaning derived data path $DD_PATH"
rm -rf "$DD_PATH"
# Also retire preferred stale install candidates from the old tool order so they cannot win find_app
for stale in \
  "$ROOT/build/DerivedData-yt3-qa/Build/Products/Release-Staging-iphoneos/YouTrader.app" \
  "$ROOT/build/DerivedData-ReleaseStaging/Build/Products/Release-Staging-iphoneos/YouTrader.app" \
  "$ROOT/build/DerivedData-yt3-qa-current"
do
  if [[ -e "$stale" ]]; then
    log "retiring_stale_candidate $stale"
    rm -rf "$stale"
  fi
done

# Archive Jul 30 is known-stale (pre NAV-1). Keep for diagnosis but exclude from install by renaming marker.
ARCHIVE_APP="$ROOT/build/YouTrader-1.6.1-113-staging.xcarchive/Products/Applications/YouTrader.app"
if [[ -d "$ARCHIVE_APP" ]]; then
  log "archive_113_present_but_excluded_from_install mtime=$(stat -f '%Sm' -t '%Y-%m-%dT%H:%M:%S' "$ARCHIVE_APP")"
fi

# Metro must be OFF
if lsof -nP -iTCP:8081 -sTCP:LISTEN >/dev/null 2>&1; then
  log "warn: Metro listening on 8081 — attempting continue; Release-Staging embeds bundle"
else
  log "metro_off=yes"
fi

log "xcodebuild Release-Staging → $DD_PATH"
set +e
xcodebuild \
  -workspace ios/YouTrader.xcworkspace \
  -scheme YouTrader-Staging \
  -configuration Release-Staging \
  -destination "generic/platform=iOS" \
  -derivedDataPath "$DD_PATH" \
  -allowProvisioningUpdates \
  DEVELOPMENT_TEAM=L6M4U8G8RC \
  CURRENT_PROJECT_VERSION="$EXPECTED_BUILD" \
  MARKETING_VERSION="$EXPECTED_VERSION" \
  build
XC_RC=$?
set -e
[[ $XC_RC -eq 0 ]] || { log "error: xcodebuild failed rc=$XC_RC"; exit "$XC_RC"; }

[[ -d "$APP_OUT" ]] || { log "error: missing app $APP_OUT"; exit 5; }
[[ -f "$APP_OUT/main.jsbundle" ]] || { log "error: embedded main.jsbundle missing"; exit 5; }

JS="$APP_OUT/main.jsbundle"
JS_SIZE="$(wc -c < "$JS" | tr -d ' ')"
[[ "$JS_SIZE" -gt 1000000 ]] || { log "error: jsbundle too small ($JS_SIZE)"; exit 5; }

APP_VER="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$APP_OUT/Info.plist")"
APP_SHORT="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP_OUT/Info.plist")"
[[ "$APP_VER" == "$EXPECTED_BUILD" ]] || { log "error: built CFBundleVersion=$APP_VER"; exit 4; }
[[ "$APP_SHORT" == "$EXPECTED_VERSION" ]] || { log "error: built short version=$APP_SHORT"; exit 4; }

FP_TOKEN="YT_BUILD_FP_v1:${GIT_SHA}:${EXPECTED_BUILD}:Release-Staging"
python3 - <<PY
from pathlib import Path
b=Path("$JS").read_bytes()
checks={
  "staging_host": b.find(b"$STAGING_HOST")>=0,
  "prod_url_absent": b.find(b"https://$PROD_HOST")<0,
  "fingerprint_prefix": b.find(b"YT_BUILD_FP_v1:")>=0,
  "git_sha": b.find(b"$GIT_SHA")>=0,
  "safe_area": b.find(b"YouTraderSafeArea")>=0,
  "qa_reset": b.find(b"reset-fresh")>=0 or b.find(b"youtrader://qa")>=0,
  "diagnostics": b.find(b"Developer Diagnostics")>=0,
  "bundle_marker": b.find(b"embedded-main.jsbundle")>=0,
  "prop_pass": b.find(b"Prop Pass")>=0 or b.find(b"propPass")>=0,
}
print(checks)
bad=[k for k,v in checks.items() if not v]
if bad:
  raise SystemExit("bundle_checks_failed:"+(",".join(bad)))
PY

# Sidecar fingerprint for physical preflight (not secrets)
FP_JSON="$APP_OUT/../YouTrader.build-fingerprint.json"
# path next to Products folder
FP_JSON="$DD_PATH/Build/Products/Release-Staging-iphoneos/YouTrader.build-fingerprint.json"
cat >"$FP_JSON" <<EOF
{
  "gitSha": "$GIT_SHA",
  "gitFull": "$GIT_FULL",
  "buildTimeUtc": "$BUILD_TIME",
  "version": "$EXPECTED_VERSION",
  "buildNumber": "$EXPECTED_BUILD",
  "xcodeConfiguration": "Release-Staging",
  "embeddedBundleMarker": "$BUNDLE_MARKER",
  "searchToken": "$FP_TOKEN",
  "appPath": "$APP_OUT",
  "jsbundleBytes": $JS_SIZE,
  "jsbundleSha256": "$(shasum -a 256 "$JS" | awk '{print $1}')",
  "navContract": "eligible:journal,propPass,stats,settings,more; deny:journal,stats,settings,more"
}
EOF
cp "$FP_JSON" "$EVID/YouTrader.build-fingerprint.json"
cp "$FP_JSON" "$ART/YouTrader.build-fingerprint-$STAMP.json"

log "build_ok app=$APP_OUT"
log "jsbundle_bytes=$JS_SIZE mtime=$(stat -f '%Sm' -t '%Y-%m-%dT%H:%M:%S' "$JS")"
log "fingerprint_token=$FP_TOKEN"
echo "$APP_OUT"
