#!/usr/bin/env bash
# Build production Release 1.6.1 (117) archive + device app from current HEAD.
# Scheme: YouTrader / Configuration: Release (NOT Release-Staging).
# Metro OFF. Production public env from .env.eas.production only.
# Does NOT upload to App Store Connect by default.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

EXPECTED_VERSION="${YT_EXPECTED_VERSION:-1.6.1}"
EXPECTED_BUILD="${YT_EXPECTED_BUILD:-117}"
DEVICE_ID="${YT_PHYSICAL_DEVICE_ID:-6FCFF771-7154-5CC0-BC29-858A3C376CAF}"
DD_PATH="${YT_RP117_DERIVED_DATA:-$ROOT/build/DerivedData-yt3-release-117}"
APP_OUT="$DD_PATH/Build/Products/Release-iphoneos/YouTrader.app"
ARCHIVE_PATH="${YT_RP117_ARCHIVE:-$ROOT/build/YouTrader-1.6.1-117.xcarchive}"
EXPORT_DIR="${YT_RP117_EXPORT:-$ROOT/build/YouTrader-1.6.1-117-export}"
IPA_PATH="${YT_RP117_IPA:-$ROOT/build/YouTrader-1.6.1-117.ipa}"
ART="${YT_QA_ARTIFACTS_DIR:-$ROOT/docs/releases/1.6.1/qa-artifacts}"
EVID="${YT_PHYSICAL_EVIDENCE_DIR:-$ROOT/docs/releases/1.6.1/evidence/build117-release-$(date -u +%Y%m%d)}"
PROD_ENV_FILE="${YT_PROD_ENV_FILE:-$ROOT/.env.eas.production}"
PROD_HOST="izzrlsgumyabdvlmwlwn.supabase.co"
STAGING_HOST="zleojeqkzizeyerhjpur.supabase.co"
BUNDLE_MARKER="embedded-main.jsbundle"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$ART" "$EVID"

GIT_SHA="$(git rev-parse --short HEAD)"
GIT_FULL="$(git rev-parse HEAD)"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

log() { echo "$*" | tee -a "$ART/build-rp117-$STAMP.log"; }

log "build_rp117 start sha=$GIT_SHA full=$GIT_FULL time=$BUILD_TIME"

ver_json="$(node -e "const a=require('./app.json'); process.stdout.write(String(a.expo?.ios?.buildNumber||''))")"
[[ "$ver_json" == "$EXPECTED_BUILD" ]] || { log "error: app.json buildNumber=$ver_json expected=$EXPECTED_BUILD"; exit 4; }

[[ -f "$PROD_ENV_FILE" ]] || { log "error: missing $PROD_ENV_FILE"; exit 2; }
grep -q "$PROD_HOST" "$PROD_ENV_FILE" || { log "error: production env missing prod host"; exit 2; }
grep -q "$STAGING_HOST" "$PROD_ENV_FILE" && { log "error: production env contains staging host"; exit 2; }

# Generated fingerprint for production (diagnostics MUST stay hidden)
cat > src/config/buildFingerprint.generated.ts <<EOF
/**
 * GENERATED — do not edit by hand.
 * Written by scripts/qa/build-release-production-117-device.sh at $BUILD_TIME
 */
export const GENERATED_APP_ENV = "production";

export const GENERATED_BUILD_FINGERPRINT = {
  gitSha: "$GIT_SHA",
  buildTimeUtc: "$BUILD_TIME",
  version: "$EXPECTED_VERSION",
  buildNumber: "$EXPECTED_BUILD",
  xcodeConfiguration: "Release",
  embeddedBundleMarker: "$BUNDLE_MARKER",
} as const;
EOF
log "wrote src/config/buildFingerprint.generated.ts"

# Local Xcode env from production EAS public env (gitignored)
{
  echo "# Generated by build-release-production-117-device.sh — DO NOT COMMIT"
  echo "export EXPO_PUBLIC_APP_ENV=production"
  echo "export APP_ENV=production"
  # shellcheck disable=SC2016
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    [[ "$key" == EXPO_PUBLIC_* || "$key" == APP_ENV ]] || continue
    printf 'export %s=%q\n' "$key" "$val"
  done < "$PROD_ENV_FILE"
  echo "export EXPO_PUBLIC_YT_GIT_SHA=$GIT_SHA"
  echo "export EXPO_PUBLIC_YT_BUILD_TIME=$BUILD_TIME"
  echo "export EXPO_PUBLIC_YT_APP_VERSION=$EXPECTED_VERSION"
  echo "export EXPO_PUBLIC_YT_BUILD_NUMBER=$EXPECTED_BUILD"
  echo "export EXPO_PUBLIC_YT_XCODE_CONFIG=Release"
  echo "export EXPO_PUBLIC_YT_BUNDLE_MARKER=$BUNDLE_MARKER"
  echo "export EXPO_PUBLIC_YT_SHOW_BUILD_FP=0"
} > ios/.xcode.env.local
log "wrote ios/.xcode.env.local from production env"

log "cleaning derived data path $DD_PATH"
rm -rf "$DD_PATH"
rm -rf "$ARCHIVE_PATH" "$EXPORT_DIR" "$IPA_PATH"

if lsof -nP -iTCP:8081 -sTCP:LISTEN >/dev/null 2>&1; then
  log "warn: Metro listening on 8081 — production Release must embed bundle"
else
  log "metro_off=yes"
fi

log "xcodebuild archive Release → $ARCHIVE_PATH"
set +e
xcodebuild \
  -workspace ios/YouTrader.xcworkspace \
  -scheme YouTrader \
  -configuration Release \
  -destination "generic/platform=iOS" \
  -archivePath "$ARCHIVE_PATH" \
  -derivedDataPath "$DD_PATH" \
  -allowProvisioningUpdates \
  CODE_SIGN_STYLE=Automatic \
  DEVELOPMENT_TEAM=L6M4U8G8RC \
  archive \
  2>&1 | tee -a "$ART/build-rp117-$STAMP.log"
XC=$?
set -e
[[ $XC -eq 0 ]] || { log "error: archive failed exit=$XC"; exit $XC; }

# Also keep device .app under Products for local install
if [[ ! -d "$APP_OUT" ]]; then
  # Fallback copy from archive
  ARCH_APP="$ARCHIVE_PATH/Products/Applications/YouTrader.app"
  if [[ -d "$ARCH_APP" ]]; then
    mkdir -p "$(dirname "$APP_OUT")"
    cp -R "$ARCH_APP" "$APP_OUT"
    log "copied archive app to $APP_OUT"
  fi
fi

# Validate identity
PLIST="$ARCHIVE_PATH/Products/Applications/YouTrader.app/Info.plist"
[[ -f "$PLIST" ]] || { log "error: missing Info.plist in archive"; exit 5; }
SHORT="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST")"
BUILD="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST")"
BUNDLE="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST")"
log "archive_identity version=$SHORT build=$BUILD bundle=$BUNDLE"
[[ "$SHORT" == "$EXPECTED_VERSION" ]] || { log "error: version mismatch"; exit 6; }
[[ "$BUILD" == "$EXPECTED_BUILD" ]] || { log "error: build mismatch"; exit 6; }
[[ "$BUNDLE" == "com.youtrader.pro" ]] || { log "error: bundle mismatch"; exit 6; }

# Scan embedded js for staging / debug markers
JS="$(find "$ARCHIVE_PATH/Products/Applications/YouTrader.app" -name 'main.jsbundle' | head -1 || true)"
[[ -n "$JS" ]] || { log "error: embedded jsbundle missing"; exit 7; }
if grep -a -q "$STAGING_HOST" "$JS"; then
  log "error: staging host found in production bundle"; exit 8
fi
if grep -a -q "Developer Diagnostics" "$JS"; then
  # staging-only UI string may still exist in source paths; ensure gate string for show path
  if grep -a -q "settings-developer-diagnostics" "$JS" && grep -a -q "YT_SHOW_BUILD_FP" "$JS"; then
    log "note: diagnostics strings present but gated"
  fi
fi
grep -a -q "$PROD_HOST" "$JS" || { log "error: production supabase host missing from bundle"; exit 9; }
grep -a -q "Release-Staging" "$JS" && { log "error: Release-Staging marker in production bundle"; exit 10; } || true
grep -a -q "OWNER_FULL_ACCESS" "$JS" && { log "error: OWNER_FULL_ACCESS in production bundle"; exit 11; } || true

# Export IPA with the explicitly authorized build 117 metadata.
mkdir -p "$EXPORT_DIR"
cat > "$EXPORT_DIR/ExportOptions.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>destination</key>
	<string>export</string>
	<key>method</key>
	<string>app-store-connect</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>L6M4U8G8RC</string>
	<key>manageAppVersionAndBuildNumber</key>
	<false/>
	<key>uploadSymbols</key>
	<true/>
</dict>
</plist>
PLIST

log "exporting IPA"
set +e
xcodebuild \
  -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportPath "$EXPORT_DIR" \
  -exportOptionsPlist "$EXPORT_DIR/ExportOptions.plist" \
  -allowProvisioningUpdates \
  2>&1 | tee -a "$ART/build-rp117-$STAMP.log"
XC=$?
set -e
[[ $XC -eq 0 ]] || { log "error: export failed exit=$XC"; exit $XC; }
cp "$EXPORT_DIR/YouTrader.ipa" "$IPA_PATH" 2>/dev/null || cp "$EXPORT_DIR"/*.ipa "$IPA_PATH"

# Fingerprint evidence
node -e "
const fs=require('fs');
const path=require('path');
const out={
  gitSha:'$GIT_SHA',
  gitFull:'$GIT_FULL',
  buildTimeUtc:'$BUILD_TIME',
  version:'$EXPECTED_VERSION',
  buildNumber:'$EXPECTED_BUILD',
  xcodeConfiguration:'Release',
  archivePath:'$ARCHIVE_PATH',
  ipaPath:'$IPA_PATH',
  appPath:'$APP_OUT',
  searchToken:'YT_BUILD_FP_v1:$GIT_SHA:$EXPECTED_BUILD:Release'
};
fs.writeFileSync('$EVID/YouTrader.build-fingerprint.json', JSON.stringify(out,null,2));
console.log(JSON.stringify(out,null,2));
"

log "build_rp117 PASS archive=$ARCHIVE_PATH ipa=$IPA_PATH"
echo "INSTALL_HINT: xcrun devicectl device install app --device $DEVICE_ID \"$APP_OUT\""
