import assert from "node:assert/strict";
import fs from "node:fs";
const index = fs.readFileSync("supabase/functions/prop-pass-runtime-processor/index.ts", "utf8");
const processor = fs.readFileSync("supabase/functions/prop-pass-runtime-processor/processor.ts", "utf8");
const hook = fs.readFileSync("src/propPass/usePropPassAvailability.ts", "utf8");
const migration = fs.readFileSync("supabase/migrations/20260802233700_prop_pass_runtime_processing_queue.sql", "utf8");
const bundle = fs.readFileSync("supabase/functions/_shared/propPassRuntime.bundle.js", "utf8");
assert.match(index, /admin\.auth\.getUser\(token\)/, "JWT must be verified, not decoded locally");
assert.match(index, /processPendingRuntimeEvents\(admin, auth\.user\.id/, "worker scope must come from verified JWT");
assert.doesNotMatch(index, /userId.*body|accountId.*body/, "caller must not choose an owner or account");
assert.match(processor, /prop_os_processor_claim_pending_journal_events/);
assert.match(processor, /rebuildPropPassRuntime/);
assert.match(processor, /prop_os_processor_complete_journal_event/);
assert.match(processor, /_shared\/propPassRuntime\.bundle\.js/);
assert.match(bundle, /build117\.pipeline\.v2/);
assert.match(processor, /The digest intentionally excludes event identity/);
assert.match(hook, /functions\.invoke\("prop-pass-runtime-processor"/);
assert.doesNotMatch(hook, /p_state_payload|complete_journal_event/);
assert.match(migration, /processing_state in \('pending', 'processing', 'applied', 'superseded', 'failed'\)/);
console.log("prop-pass-runtime-processor-qa: PASS");
