import assert from "node:assert/strict";
import { createDailyTradingPlan } from "../src/propPass/tradingOs";
const input = { snapshotId: "plan-1", generatedAt: "2026-08-02T12:00:00Z", account: { contextType: "challenge" as const, accountId: "qa", startingBalanceMinor: 500_000, currentBalanceMinor: 500_000, currentEquityMinor: 500_000, equityHighMinor: 500_000, realizedPnlMinor: 0, tradingDay: "2026-08-02", timezone: "America/New_York", preferredInstrument: "QA" }, challengeRules: { id: "rules", effectiveDate: "2026-08-02", templateVersion: "qa", stopAfterLosses: 2, profitLockMinor: 40_000 }, liveRules: null, riskRooms: { dailyLossRemainingMinor: 100_000, maximumLossRemainingMinor: 90_000, drawdownRemainingMinor: 80_000, configuredDailyRiskBudgetMinor: 70_000, configuredPerTradeRiskCapMinor: 60_000 }, selectedMode: "balanced" as const, preferredInstrument: null, intendedSessionId: "ny-am", instrumentSpecificationVersion: "qa-v1", recentLossStreak: 0 };
const created = createDailyTradingPlan(input);
assert.equal(created.status, "safe_to_take");
assert.equal(created.values?.riskPerTradeMinor, 13_500);
assert.equal(created.values?.maximumRiskTodayMinor, 60_000);
assert.equal(Object.isFrozen(created.values), true);
assert.equal(createDailyTradingPlan({ ...input, recentLossStreak: 2 }).status, "stop_trading");
assert.equal(createDailyTradingPlan({ ...input, riskRooms: { ...input.riskRooms, drawdownRemainingMinor: null } }).status, "needs_input");
console.log("prop-pass-daily-plan-qa: PASS");
