import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const baseSql = fs.readFileSync(path.resolve(__dirname, "../supabase/migrations/20260802212828_prop_pass_trading_os_persistence.sql"), "utf8");
const hardeningSql = fs.readFileSync(path.resolve(__dirname, "../supabase/migrations/20260802223818_prop_pass_build117_persistence_hardening.sql"), "utf8");
const journalSyncSql = fs.readFileSync(path.resolve(__dirname, "../supabase/migrations/20260802225538_prop_pass_journal_automatic_sync.sql"), "utf8");
const pipelineV2Sql = fs.readFileSync(path.resolve(__dirname, "../supabase/migrations/20260802232311_prop_pass_pipeline_v2_runtime.sql"), "utf8");
const runtimeQueueSql = fs.readFileSync(path.resolve(__dirname, "../supabase/migrations/20260802233700_prop_pass_runtime_processing_queue.sql"), "utf8");
const settingsQueueSql = fs.readFileSync(path.resolve(__dirname, "../supabase/migrations/20260802235500_prop_pass_settings_recalculation_events.sql"), "utf8");
const sql = `${baseSql}\n${hardeningSql}\n${journalSyncSql}\n${pipelineV2Sql}\n${runtimeQueueSql}\n${settingsQueueSql}`;
const tables = ["prop_daily_plan_snapshots", "prop_pre_trade_assessments", "prop_rule_templates", "prop_intervention_events", "prop_timeline_events", "prop_live_risk_settings", "prop_payout_withdrawal_settings", "prop_kill_switch_settings", "prop_position_size_progressions", "prop_recovery_mode_states"];
for (const table of tables) assert.match(sql, new RegExp(`'${table}'`), `${table} must be RLS-scoped`);
assert.match(sql, /enable row level security/); assert.match(sql, /force row level security/); assert.match(sql, /to authenticated using \(user_id = \(select auth\.uid\(\)\)\)/);
assert.match(sql, /revoke all on table public\.%I from public, anon, authenticated/); assert.doesNotMatch(sql, /provider_token|identity_token|authorization_code/i);
assert.match(sql, /unique \(user_id, event_key\)/, "event persistence must support idempotency");
assert.match(sql, /append_only/, "historical plans and events must stay immutable");
for (const table of ["prop_instrument_spec_versions", "prop_intervention_overrides", "prop_decision_replays", "prop_processed_journal_events", "prop_account_runtime_states"]) {
  assert.match(hardeningSql, new RegExp(`'${table}'`), `${table} must be owner-scoped and RLS protected`);
}
assert.match(hardeningSql, /journal_event_identity_mismatch/);
assert.match(hardeningSql, /state_revision_digest_mismatch/);
assert.match(hardeningSql, /grant execute on function public\.prop_os_processor_claim_journal_event[\s\S]+to postgres, service_role/);
assert.doesNotMatch(hardeningSql, /grant execute on function public\.prop_os_processor_[^(]+\([^;]+to authenticated/);
assert.match(hardeningSql, /plan snapshot must belong to user and account/);
assert.doesNotMatch(hardeningSql, /provider_token|identity_token|authorization_code/i);
assert.match(journalSyncSql, /prop_pass_revision/);
assert.match(journalSyncSql, /prop_pass_journal_material_changed/);
assert.match(journalSyncSql, /prop_pass_journal_sync_after_update/);
assert.match(journalSyncSql, /prop_os_assignment_queue_recalc/);
assert.match(journalSyncSql, /update public\.prop_executions set voided = true/);
assert.match(journalSyncSql, /on conflict \(user_id, event_key\) do nothing/);
assert.match(journalSyncSql, /revoke all on function public\.prop_pass_journal_sync_after_update\(\) from public, anon, authenticated/);
assert.doesNotMatch(journalSyncSql, /provider_token|identity_token|authorization_code/i);
assert.match(pipelineV2Sql, /build117\.pipeline\.v2/);
assert.match(pipelineV2Sql, /before insert on public\.prop_processed_journal_events/);
assert.match(pipelineV2Sql, /revoke all on function public\.prop_pass_stamp_current_calculation_version\(\)/);
assert.doesNotMatch(pipelineV2Sql, /delete from|drop table|provider_token|identity_token|authorization_code/i);
assert.match(runtimeQueueSql, /prop_os_processor_claim_pending_journal_events/);
assert.match(runtimeQueueSql, /for update skip locked/);
assert.match(runtimeQueueSql, /from public, anon, authenticated/);
assert.match(runtimeQueueSql, /'pending', null/);
assert.doesNotMatch(runtimeQueueSql, /grant execute[\s\S]*to authenticated/);
assert.match(settingsQueueSql, /'settings_changed'/);
assert.match(settingsQueueSql, /prop_os_processor_queue_settings_recalculation/);
assert.match(settingsQueueSql, /from public, anon, authenticated/);
assert.doesNotMatch(settingsQueueSql, /grant execute[\s\S]*to authenticated/);
