-- Prop Firm Risk Assistant: configurable templates from Supabase (no app hardcoding).

alter table public.prop_firms
  add column if not exists company text,
  add column if not exists profit_target numeric,
  add column if not exists static_drawdown numeric,
  add column if not exists trailing_drawdown_amount numeric,
  add column if not exists consistency_rule jsonb not null default '{}'::jsonb,
  add column if not exists min_trading_days integer not null default 0,
  add column if not exists scaling_rules jsonb not null default '{}'::jsonb,
  add column if not exists news_restrictions jsonb not null default '{}'::jsonb,
  add column if not exists weekend_holding_allowed boolean not null default false,
  add column if not exists payout_rules jsonb not null default '{}'::jsonb,
  add column if not exists last_verified date,
  add column if not exists source_url text,
  add column if not exists supported_phases text[] not null default array['evaluation', 'funded']::text[],
  add column if not exists is_custom boolean not null default false,
  add column if not exists updated_at timestamptz not null default now();

alter table public.user_firm_settings
  add column if not exists template_slug text,
  add column if not exists account_phase text not null default 'evaluation'
    check (account_phase in ('evaluation', 'challenge', 'funded', 'live')),
  add column if not exists current_balance numeric,
  add column if not exists overrides jsonb not null default '{}'::jsonb,
  add column if not exists custom_company text;

update public.prop_firms
set
  company = coalesce(company, name),
  profit_target = coalesce(profit_target, round(account_size * 0.06)),
  static_drawdown = coalesce(static_drawdown, case when trailing_drawdown then null else max_loss_limit end),
  trailing_drawdown_amount = coalesce(trailing_drawdown_amount, case when trailing_drawdown then max_loss_limit else null end),
  source_url = coalesce(source_url, (rules->>'sourceUrl')),
  last_verified = coalesce(last_verified, created_at::date)
where company is null or profit_target is null;

insert into public.prop_firms (
  slug,
  name,
  company,
  account_name,
  account_size,
  daily_loss_limit,
  max_loss_limit,
  evaluation_contracts,
  live_contracts,
  trailing_drawdown,
  trailing_drawdown_amount,
  static_drawdown,
  profit_target,
  min_trading_days,
  consistency_rule,
  scaling_rules,
  news_restrictions,
  weekend_holding_allowed,
  payout_rules,
  last_verified,
  source_url,
  supported_phases,
  is_custom,
  rules
) values
  (
    'topstep-50k-eval',
    'Topstep',
    'Topstep',
    '50K Trading Combine',
    50000,
    1000,
    2000,
    5,
    3,
    false,
    null,
    2000,
    3000,
    5,
    '{"maxDailyProfitPct":50,"description":"Best day cannot exceed 50% of total profit target"}'::jsonb,
    '{"evaluation":{"maxContracts":5},"funded":{"maxContracts":3,"scaleAfterDays":10}}'::jsonb,
    '{"bufferMinutes":2,"highImpactOnly":true}'::jsonb,
    false,
    '{"minDays":5,"maxWithdrawPct":50}'::jsonb,
    '2026-06-01',
    'https://www.topstep.com/trading-combine/',
    array['evaluation', 'funded', 'live']::text[],
    false,
    '{"evaluationRiskPct":0.1,"liveRiskPct":0.08,"drawdownType":"static"}'::jsonb
  ),
  (
    'apex-50k-eval',
    'Apex',
    'Apex',
    '50K Evaluation',
    50000,
    1250,
    2500,
    10,
    5,
    true,
    2500,
    null,
    3000,
    7,
    '{"trailingStopsAtBalance":true}'::jsonb,
    '{"evaluation":{"maxContracts":10},"funded":{"maxContracts":5}}'::jsonb,
    '{"bufferMinutes":1,"highImpactOnly":true}'::jsonb,
    true,
    '{"minDays":8,"profitSplitPct":90}'::jsonb,
    '2026-06-01',
    'https://apextraderfunding.com/',
    array['evaluation', 'funded']::text[],
    false,
    '{"evaluationRiskPct":0.1,"liveRiskPct":0.075,"drawdownType":"trailing"}'::jsonb
  ),
  (
    'take-profit-trader-50k',
    'Take Profit Trader',
    'Take Profit Trader',
    '50K Pro Account',
    50000,
    1100,
    2200,
    5,
    3,
    false,
    null,
    2200,
    3000,
    5,
    '{"consistencyPct":50}'::jsonb,
    '{"evaluation":{"maxContracts":5},"funded":{"maxContracts":3}}'::jsonb,
    '{"bufferMinutes":2,"highImpactOnly":true}'::jsonb,
    false,
    '{"minDays":5,"maxWithdrawPct":50}'::jsonb,
    '2026-06-01',
    'https://takeprofittrader.com/',
    array['evaluation', 'challenge', 'funded']::text[],
    false,
    '{"evaluationRiskPct":0.1,"liveRiskPct":0.08,"drawdownType":"static"}'::jsonb
  ),
  (
    'lucid-100k-eval',
    'Lucid',
    'Lucid',
    '100K Evaluation',
    100000,
    2000,
    3000,
    10,
    6,
    true,
    3000,
    null,
    6000,
    10,
    '{"trailingStopsAtBalance":true}'::jsonb,
    '{"evaluation":{"maxContracts":10},"funded":{"maxContracts":6}}'::jsonb,
    '{"bufferMinutes":2,"highImpactOnly":true}'::jsonb,
    true,
    '{"minDays":10,"profitSplitPct":90}'::jsonb,
    '2026-06-01',
    'https://lucidtrading.com/',
    array['evaluation', 'funded']::text[],
    false,
    '{"evaluationRiskPct":0.095,"liveRiskPct":0.075,"drawdownType":"trailing"}'::jsonb
  ),
  (
    'custom-template',
    'Custom Firm',
    'Custom',
    'Custom Account',
    50000,
    1000,
    2000,
    5,
    3,
    false,
    null,
    2000,
    3000,
    0,
    '{}'::jsonb,
    '{"evaluation":{"maxContracts":5},"funded":{"maxContracts":3}}'::jsonb,
    '{}'::jsonb,
    true,
    '{}'::jsonb,
    current_date,
    null,
    array['evaluation', 'challenge', 'funded', 'live']::text[],
    true,
    '{"evaluationRiskPct":0.1,"liveRiskPct":0.08,"drawdownType":"static"}'::jsonb
  )
on conflict (slug) do update set
  name = excluded.name,
  company = excluded.company,
  account_name = excluded.account_name,
  account_size = excluded.account_size,
  daily_loss_limit = excluded.daily_loss_limit,
  max_loss_limit = excluded.max_loss_limit,
  evaluation_contracts = excluded.evaluation_contracts,
  live_contracts = excluded.live_contracts,
  trailing_drawdown = excluded.trailing_drawdown,
  trailing_drawdown_amount = excluded.trailing_drawdown_amount,
  static_drawdown = excluded.static_drawdown,
  profit_target = excluded.profit_target,
  min_trading_days = excluded.min_trading_days,
  consistency_rule = excluded.consistency_rule,
  scaling_rules = excluded.scaling_rules,
  news_restrictions = excluded.news_restrictions,
  weekend_holding_allowed = excluded.weekend_holding_allowed,
  payout_rules = excluded.payout_rules,
  last_verified = excluded.last_verified,
  source_url = excluded.source_url,
  supported_phases = excluded.supported_phases,
  is_custom = excluded.is_custom,
  rules = excluded.rules,
  updated_at = now();
